const actionTypes = {
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGIN_FALIURE: 'LOGIN_FALIURE',
  FETCH_ALL_PRODUCTS: 'FETCH_ALL_PRODUCTS',
  REGISTER_SUCCESSFUL: 'REGISTER_SUCCESSFUL',
  REGISTER_FALIURE: 'REGISTER_FALIURE',
};

export default actionTypes;
